spring:
# Postgres Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/onlineshoppingdb
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.MYSQLDialect
        format_sql: true
    
        
        

#SMTP Configuration

  mail: 
    host: smtp.gmail.com
    username: inbakumari99@gmail.com
    password: qify ktkw sboh mmdw
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true  
        